{% set name = "mapkit" %}
{% set version = "1.2.5" %}
{% set sha256 = "24d495fa80a3910a6f6965bd7fef90fd3f3be5df428ccb74f5ee46a9fa218c9a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - requests
    - sqlalchemy

test:
  imports:
    - mapkit
    - mapkit.RasterConverter
    - mapkit.GeometryConverter
    - mapkit.RasterLoader
    - mapkit.sqlatypes

about:
  home: https://github.com/CI-WATER/mapkit
  license: BSD-2-Clause
  license_family: BSD
  summary: 'A Python module with mapping functions for PostGIS enabled PostgreSQL databases.'
  description: |
    MapKit is a Python module with mapping functions for PostGIS enabled
    PostgreSQL databases.
  dev_url: https://github.com/CI-WATER/mapkit

extra:
  recipe-maintainers:
    - swainn
    - snowman2
