travis:
  secure:
    BINSTAR_TOKEN: p5TPOFsPT0OnZ1arf4qaVKP4tRaHXKeF+dLJVvHaVAIjqAPZRyphDeEx3hZXgSO3iiMghbCDH+BLgcOgONx8hmIM9wTnOziW2QBcgILhjVpSWE8Vo4Se3UQBLzNcHyucZZJDpfHUCexBQH29y5qhXxZq2ZhBaQBl2EiI+cSghmfzeOpN4+HnlUCkWrxlNOA0mVOk+543QMlUOUyuiFWKn1TZ30NUFgCUN2+cGBZ10ZrHF2y/Use6b/Zd38VLlXCJRpJOt4NlhEgd8H25ykRzXkd7lpbBoWrMuXSI99LvJ9tkuU8Ht0UhrAA362TMLzkF9rXKotNctkXLUBTM8uqVVLmIo3EQXQvWOjE/kaa/xHdU7Ltq1FoQmtKcBobTakXIhg0qv3boRmIEQo039sFxpq4gU9DPrzxBr2t1RfCKHrIfzUb4bsqMDQbWOYZfoLHFVekDgXcTNYfLZ54JOYyk+BmEnRvVuFjVh0l4xWjCWrxxcPRlMOMeoin0JnZJ4/BG+0/u3GXCbeqwBTTO8ocpCCQ3aWxWCop3NFGadG/17bGh/u4oZi7pIuU25fZg9elGOj02eo1dBGQiN6LUJt9vPhxdyfQmD5lkwB6E8GdhAwHXwptI+cmD39KslV4yt1LdkHvrwcndoJjJJH4qRfxaoNMBNGNO/39GtF1la2Mre3U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
